### ISSUE TITLE
Permitir el uso de mayúsculas

### ISSUE THREAD

**Issue by 9-natalia** [OswaldoAD/Trivia-Metalera-lml#3]
### **Problema**

Cuando intento ingresar mi respuesta en la preguntas no me permite poner las alternativas a, b, c o d en mayúsculas y me dice que las escriba de nuevo, eso ocurre con todas las preguntas. 

 ### **Consola**
![image](https://user-images.githubusercontent.com/113303509/190840501-762392a5-24e7-4c4f-be5e-7b1bfca172e2.png)

 ### **Posible solución**
Agregar lower() para que no importe que el usuario use mayúsculas.
`respuesta_1 = input(YELLOW+"\n Tu respuesta: "+MAGENTA).lower()`
También en el caso de que se equivoque y se tenga que repetir de nuevo agregarle ahí también lower() para que así no le salgo como si fuera un error.
`respuesta_1 = input(BLUE+"Debes responder a,b,c o d. Ingresa nuevamente tu respuesta: ").lower()`

**Comment by OswaldoAD** [comment]
No tome en cuenta esa posibilidad, lo corregiré
Gracias por el aporte
