### ISSUE TITLE
Limpiar pantalla

### ISSUE THREAD

**Issue by 9-natalia** [OswaldoAD/Trivia-Metalera-lml#4]
### **Problema**
Al reintentar en la trivia se queda acumulado todas mis respuestas de mis intentos anteriores.

![image](https://user-images.githubusercontent.com/113303509/190840900-f7c5537f-1a59-4d37-9a4d-4fa2b664f8ef.png)

### **Posible solución**
Podrías poner `print("\033c", end="")` para tener de nuevo una hoja en blanco a la hora de reintentar la trivia.

**Comment by OswaldoAD** [comment]
Entiendo, a lo que te refieres es que la consola queda cargada  con la introducción, preguntas, respuestas, etc. Implementare tu sugerencia de limpieza , gracias por el aporte.
