### ISSUE TITLE
Pregunta 4, opción

### ISSUE THREAD

**Issue by 9-natalia** [OswaldoAD/Trivia-Metalera-lml#5]
En la pregunta 4 si ejecutamos la opción 'a', nos dividen los puntos pero si los puntos anteriores eran negativos no se cambia la forma simplemente se dividen; por lo cual a pesar de que elegimos la opción incorrecta sale a nuestro favor la división.
https://github.com/OswaldoAD/Trivia-Metalera-lml/blob/e311cf8bed78a6cf162c80ec9ab9682e9ba30a30/main.py#L123-L126
En cambio en si vemos la opción 'd', aquí si hay otro método que propone si es que el puntaje es negativo.
https://github.com/OswaldoAD/Trivia-Metalera-lml/blob/e311cf8bed78a6cf162c80ec9ab9682e9ba30a30/main.py#L135-L141

> Opino que al igual que la opción 'd' también aplique lo mismo en la 'a' para que el puntaje si es negativo se le reste o multiplique.

**Comment by OswaldoAD** [comment]
Revisado y corregido, se agradece la observación
